# Generated by Django 5.0.3 on 2024-03-13 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_active', models.BooleanField(default=True, verbose_name='Общаются ли?')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес доставки альтушки')),
                ('altushka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='altushka', to=settings.AUTH_USER_MODEL, verbose_name='Альтушка')),
                ('scuf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scuf', to=settings.AUTH_USER_MODEL, verbose_name='Скуф')),
            ],
        ),
    ]
