# Generated by Django 5.0.3 on 2024-03-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Общаются ли?'),
        ),
    ]
